chore: MyPy requires `Optional` for `None` default (#214)
The current version of `black` threw the following error:
```
piquasso/_math/fock.py:465: error: Incompatible default for argument "d" (default has type "None", argument has type "int")  [assignment]
piquasso/_math/fock.py:465: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
piquasso/_math/fock.py:465: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
```

The error message speaks for itself, so the required changes were made
in the codebase.