fix(requirements.txt): Bumping `black` version
Running `black` resulted in the error
```
ImportError: cannot import name '_unicodefun' from 'click'
```
since the most recent release of `click` breaks `black`. However, this
has been fixed in `black==22.3.0`.

Issue: https://github.com/psf/black/issues/2964