dev(requirements): `flake8` upgrade
The pipeline run resulted in the following error:
```
AttributeError: 'EntryPoints' object has no attribute 'get'
```
It is because `flake8==4.0.1` might used a deprecated endpoint of
`importlib_metadata`. Therefore it has been upgraded.

Source:
- https://importlib-metadata.readthedocs.io/en/latest/history.html